export default {
  // Token header
  TOKEN_HEADER: "Authorization",
  TOKEN_START: "Bearer ",

  AUTHORITIES: ["ADMIN", "TENANT", "CUSTOMER"],
  
  ROLE_ADMIN: 'ADMIN',
  ROLE_TENANT: 'TENANT',
  ROLE_CUSTOMER: 'CUSTOMER',

  // DEVICE_CREDENTIALS
  DEVICE_CREDENTIALS_TYPE_ACCESS_TOKEN: "ACCESS_TOKEN",
  DEVICE_CREDENTIALS_TYPE_X_509: "X509_CERTIFICATE",
  DEVICE_CREDENTIALS_TYPE_MQTT_BASIC: "MQTT_BASIC",

  // WIDGETS BUNDLE
  DEFAULT_WIDGETS_BUNDLE: {
    CHARTS: "charts",
    ANALOGUE_GAUGES: "analogue_gauges"
  }
};
